---
- name: Install Venom
  hosts: nodes
  become: True
  gather_facts: False

  collections:
    - inverse_inc.utils

  vars:
    venom__version: 'v1.0.1'
    
  roles:
    - role: venom
      tags: venom
