---
- name: Install Venom
  hosts: pfservers, service_venom
  become: True
  gather_facts: False

  collections:
    - inverse_inc.utils

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  roles:
    - role: venom
      tags: venom
