- hosts: pfservers
  name: Configure iptables
  become: True
  gather_facts: False

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  tasks:
  - import_tasks: tasks/vagrant_iptables.yml
