- hosts: standalones
  name: Enable IPv6 in generic EL images
  become: True
  gather_facts: False

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  tasks:
    - name: Remove sysctl config defined in upstream Vagrant images
      ansible.posix.sysctl:
        name: 'net.ipv6.conf.all.disable_ipv6'
        state: 'absent'
        reload: yes
      when: ansible_os_family == 'RedHat'

