- hosts: pfservers
  name: configure Golang environment for unit tests
  become: True
  gather_facts: False

  collections:
    - inverse_inc.packetfence

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  roles:
    - role: packetfence_go
      tags: go
