- hosts: pfservers
  name: Register RHEL subscription
  become: True
  gather_facts: False
  tags: register

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  tasks:
    - name: Include tasks to register RHEL systems
      include_tasks: tasks/register_rhel_subscription_tasks.yml
      when: ansible_os_family == 'RedHat'
