- hosts: pfservers
  name: Set venom vars
  become: True
  gather_facts: False

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  tasks:
  # packetfence-test or {{ venom_dir }}/vars/local.yml should exist
  - import_tasks: tasks/install_venom_local_vars.yml
