- hosts: pfservers
  name: Unregister RHEL subscription
  become: True
  gather_facts: False
  tags: unregister

  pre_tasks:
  - name: Gather distribution only
    ansible.builtin.setup:
      gather_subset:
        - "!all"
        - "!min"
        - "distribution"

  tasks:
    - name: Include tasks to unregister RHEL systems
      include_tasks: tasks/unregister_rhel_subscription_tasks.yml
      when: ansible_os_family == 'RedHat'
