- hosts: service_tinyproxy
  name: Manage Tinyproxy service
  become: True
  gather_facts: False

  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  pre_tasks:
  - name: Gather min only
    ansible.builtin.setup:
      gather_subset:
        - "!all"

  roles:
    - role: tinyproxy
